OBJS = 1.10_for 1.10_while 1.11_for 1.11_while \
       1.14 1.15 1.16 1.18 1.19 1.20 1.21 1.22 \
       1.24 1.25 1.3 1.4 1.5 minus
CFLAGS = -I ../include
LDFLAGS = -I ../include

all: $(OBJS)

1.10_for :
1.10_while :
1.11_for :
1.11_while :
1.14 :
1.15 :
1.16 :
1.18 :
1.19 :
1.20 :
1.21 : ../lib/Sales_item.cc
1.22 : ../lib/Sales_item.cc
1.24 : ../lib/Sales_item.cc
1.25 : ../lib/Sales_item.cc
1.3 :
1.4 :
1.5 :
minus :

.PHONY: clean
clean:
	-rm -fr $(OBJS)
